### ISSUE TITLE
Update from HTTP/1.1 to HTTP/2

### ISSUE THREAD

**Issue by debck** [Ignitus/Ignitus-client#138]
Currently our project uses HTTP/1.1 version.
We should update to HTTP/2.0 as it has many features which would also enhance issue here #109 (to increase PWA features)

* HTTP/2 supports queries multiplexing, headers compression, priority and more intelligent packet streaming management.

**Comment by divyanshu-rawat** [comment]
@debck Thanks for pointing this out 👍

**Comment by CDharmateja** [comment]
@divyanshu-rawat I see that we are using docker. Since the code is static and we are not using server side rendering, I think going serverless would be beneficial both in terms of scalability and cost. Additionally most of the online services provide https and http2 out of the box. If we are going to stick with docker then I think we need to first use certbot which provide free ssl certificate from Let's Encrypt and use nginx server for http2 in docker. I am new to docker but I can try implementing.
