### ISSUE TITLE
Delay in rendering of testimonials.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#208]
**Describe the bug**
First slide of Testimonials is taking time to re-render this is beacuse of the time interval that we set for `automatic` slide change, so 1st slide is poping up after `1700ms` because we have designed it to do so, but that is a software design mistake I think, we wanted to have a interval of `1700ms` between each consecutive slide excluding the 1st one, in summary we didn't wanted the first silde to pop up after `1700 ms`.

**To Reproduce**
1. Go to 'www.ignitus.org'.
2. Scroll down to testimonial section, you will be noticing a slight delay until 1st slide shows up.

**Expected behavior**
No delay in occurence of 1st slide, rest of the slides will be shown with an interval of `1700ms`.

**Desktop:**
 - All OS
 -  All Browser [e.g. chrome, safari]

**Additional context**

File and line responsible for bug: 
https://github.com/Ignitus/Ignitus-Client-Side-Development/blob/master/src/ignitus-Testimonial/Components/Testimonial.js#L88

**Comment by laurent-kouassi** [comment]
Maybe the problem is not the slide @divyanshu-rawat 
- Slide Working Fine 
- Delay working fine 

Are the cards attached to the slide content? 
My answer is no. :)

Self Suggested Solution Is To  Render Each Side Inside Each Card.
ps: These might be Boostrap carousel card, what of if the design was implemented with Materialize?

I will try to link the slide to the carousel card first if that would works. If not , it would work hahaha

Guys if it take time , it is because i am new to React And Also coding a social media apps for my Thesis Project. But surely, i will get this fixed. ;) 

Have A Great And Lovely Day, 
Love :)

**Comment by divyanshu-rawat** [comment]
@laurent-kouassi feel free to take as much time as you want that's fine 👍 .
