### ISSUE TITLE
Err messages not hiding.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-client#404]
**Describe the bug**

**To Reproduce**
1. Go to www.ignitus.org
2. Click on SignIn, 
3. Select student SignIn that will take you here. http://www.ignitus.org/login/student
4. Try authenticating with wrong, credentials, you will see an `err` that say `processing`.
5. Now If you navigate to SignUp let's say, and come back to SignIn again, you will still see the `err`.

**Expected behavior**
Err messages should be gone as soon as we leave the current page, but currently they stay there.

**Screenshots**
<img width="748" alt="Screenshot 2019-12-07 at 00 09 06" src="https://user-images.githubusercontent.com/13464678/70364602-745e1680-188d-11ea-88dc-26369ea444d1.png">

<img width="740" alt="Screenshot 2019-12-07 at 01 35 33" src="https://user-images.githubusercontent.com/13464678/70365526-18e25780-1892-11ea-89d7-c4868e12dfb0.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Improve UX.

**Comment by abhu-A-J** [comment]
@divyanshu-rawat  I was just trying to work on this issue so see if I can figure it out, and it seems the problem was with the reducer in **LOG_IN_RESPONSE** where the message key was not reset to `' '`.

This would the solution but that creates a new problem on the UI which is the loader component and the message `Processing...` is kind of equivalent to what they offer. So I overcame the solution by removing the loader and adding the message `Processing...` while the user info is being fetched. (since both implies waiting time) . Then if it's a success it'll redirect as usual like previous cases, and if not it will remove the processing message from UI, since the  **LOG_IN_RESPONSE** resets the message to `' '`. And the bug for message retainment is removed. It kinda looks like this:

If this is okay, then I'll like to take this issue and also address #399  on the same go, since it uses lodash method `isEmpty` to it which should be not be hard to replicate.

![Ignitus](https://user-images.githubusercontent.com/49617450/76539117-544e7c80-64a6-11ea-8ef3-ce4d8048966f.gif)

**Comment by divyanshu-rawat** [comment]
> @divyanshu-rawat I was just trying to work on this issue so see if I can figure it out, and it seems the problem was with the reducer in **LOG_IN_RESPONSE** where the message key was not reset to `' '`.
> 
> This would the solution but that creates a new problem on the UI which is the loader component and the message `Processing...` is kind of equivalent to what they offer. So I overcame the solution by removing the loader and adding the message `Processing...` while the user info is being fetched. (since both implies waiting time) . Then if it's a success it'll redirect as usual like previous cases, and if not it will remove the processing message from UI, since the **LOG_IN_RESPONSE** resets the message to `' '`. And the bug for message retainment is removed. It kinda looks like this:
> 
> If this is okay, then I'll like to take this issue and also address #399 on the same go, since it uses lodash method `isEmpty` to it which should be not be hard to replicate.
> 
> ![Ignitus](https://user-images.githubusercontent.com/49617450/76539117-544e7c80-64a6-11ea-8ef3-ce4d8048966f.gif)

Thanks replied in slack :)
