### ISSUE TITLE
Change the logo color dynamically

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-client#540]
**Describe the bug**
In the Signup/login page, the logo on the left is not visible because of the color. 

**Expected behavior**
The logo SVG color needs to be dynamically changed to white or blue based on the background navbar color, to make it visible. 

**Screenshots**
Current screen with blue color logo on the blue navbar.
<img width="1440" alt="Screenshot 2020-03-01 at 12 12 31 AM" src="https://user-images.githubusercontent.com/26546816/75616459-613ba980-5b51-11ea-8386-4dc6123af72c.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by APOORVA456** [comment]
@Paarmita  I would Like to work on this issue .

**Comment by gittysachin** [comment]
Sure @APOORVA456, Go ahead 👍

**Comment by Paarmita** [comment]
@APOORVA456 Are you still working on this one, because as I plan to make the navbar constant so this issue doesn't make sense now.

**Comment by APOORVA456** [comment]
Oh Okay

**Comment by gittysachin** [comment]
@Paarmita I think that navbar should not be constant for each page and every scroll position. That would be cool if we can identify the background color of the page then we can make keep changing the colors inside the navbar and its logo. It should work like this. If the background color of the page at starting is `#010066` then we should change the logo color to `white` otherwise the color as it is. On the homepage, firstly logo color is black, which looks awesome then after scrolling it changes to `#010066`. That is cool too, though it gets blurred. We need to fix that. 

On the other pages, like signup, everything looks but the black logo is not visible. This issue will fix that problem. I don't think that making the navbar constant would be more suitable. What are your thoughts @divyanshu-rawat?

**Comment by Paarmita** [comment]
@gittysachin Good point. But for pages like `UIkit`, `Notfound`, `Site under construction`, `Careers`,  `Authentication- login signup` We need the navbar constant as initially, it has a transparent background which is not visible on these pages. 
@divyanshu-rawat What could be a good workaround for this issue?

**Comment by Paarmita** [comment]
@APOORVA456 You can take up this one now, as we discussed that it makes sense.
